name = "zotero-archive-proxy"
main = "archive-proxy.js"
compatibility_date = "2024-05-24"

# Production route
# route = { pattern = "archive-proxy.your-domain.workers.dev/*", zone_name = "your-domain.com" }

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Environment variables (if needed)
# [vars]
# ALLOWED_ORIGINS = "chrome-extension://*,moz-extension://*"

# Rate limiting (optional)
# [[rules]]
# type = "ratelimit"
# match = "/*"
# threshold = 100
# period = 3600
# action = "challenge"