// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoArchive": boolean;
      "defaultService": string;
      "iaTimeout": number;
      "iaMaxRetries": number;
      "iaRetryDelay": number;
      "robustLinkServices": string;
      "fallbackOrder": string;
      "checkBeforeArchive": boolean;
      "archiveAgeThresholdHours": number;
      "skipExistingMementos": boolean;
      "enableInternetArchive": boolean;
      "enableArchiveToday": boolean;
      "enableArquivoPt": boolean;
      "enablePermaCC": boolean;
      "enableUKWebArchive": boolean;
      "preferDOI": boolean;
    };
  }
}
